### PR TITLE
Implement `core::fmt::Step` for `UInt`

### LINKED ISSUE #29: Range iterators?
Currently it is not possible to do something like
```rust
for n in u5::MIN..u5::MAX {
    //...
}
```

Implementing this would be possible if/when [`step_trait`](https://github.com/rust-lang/rust/issues/42168) is stable.

Alternatively it is possible to create a new range-like type which implements `IntoIterator`, produced by something like `u5::range(u5::MIN, u5::MAX)`. The downside of course is that this function would become unnecessary if `step_trait` is stabilized.

### PR DESCRIPTION
**Pull request by pickx**
Closes #29.

### CODE REVIEW

**Comment by danlehmann** [comment]
This looks great, thanks a lot for the contribution.

1. We should have tests to ensure both the arbitrary int overflowing as well as the underlying type overflowing. I wrote them up (and they pass just fine):


```
#[cfg(feature = "step_trait")]
#[test]
fn forward_out_of_range() {
    // In range
    assert_eq!(Some(u7::new(121)), Step::forward_checked(u7::new(120), 1));
    assert_eq!(Some(u7::new(127)), Step::forward_checked(u7::new(120), 7));

    // Out of range
    assert_eq!(None, Step::forward_checked(u7::new(120), 8));

    // Out of range for the underlying type
    assert_eq!(None, Step::forward_checked(u7::new(120), 140));
}

#[cfg(feature = "step_trait")]
#[test]
fn backward_out_of_range() {
    // In range
    assert_eq!(Some(u7::new(1)), Step::backward_checked(u7::new(10), 9));
    assert_eq!(Some(u7::new(0)), Step::backward_checked(u7::new(10), 10));

    // Out of range
    assert_eq!(None, Step::backward_checked(u7::new(10), 11));
}
```

**Comment by danlehmann** [comment]
2. Github's test runner won't currently test this, as the feature needs to be enabled. We can add that:

In .github/workflows, make a copy of test-const.yml and swap out the feature.

Once that is added and uploaded, Github should automatically run the test suite with this feature enabled.

**Comment by danlehmann** [comment]
Oh! And:

3. Add the new feature to the CHANGELOG.md, putting it under a new section 1.2.7

**Comment by pickx** [comment]
thanks for the guidance! please let me know if there's anything else I'm missing

**Review by danlehmann — APPROVED** [review]

**Comment by danlehmann** [comment]
Thanks a lot for your contribution!

**Pull request merged**
